# Generated by Django 4.2.7 on 2025-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resend_api_key',
            field=models.CharField(blank=True, help_text='Your Resend API key for sending emails', max_length=255, verbose_name='Resend API key'),
        ),
        migrations.AddField(
            model_name='user',
            name='resend_from_email',
            field=models.EmailField(blank=True, help_text='Email address to send emails from (must be verified in Resend)', max_length=254, verbose_name='From email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='resend_from_name',
            field=models.CharField(blank=True, help_text='Name to display in "from" field of emails', max_length=200, verbose_name='From name'),
        ),
    ]
