# Generated by Django 4.2.7 on 2025-10-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='variable name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('variable_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('image', 'Image')], max_length=20, verbose_name='variable type')),
                ('example_value', models.CharField(max_length=200, verbose_name='example value')),
                ('applies_to', models.CharField(help_text='invoice, offer, or both', max_length=50, verbose_name='applies to')),
            ],
            options={
                'verbose_name': 'template variable',
                'verbose_name_plural': 'template variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice'), ('offer', 'Offer')], max_length=20, verbose_name='template type')),
                ('is_default', models.BooleanField(default=False, verbose_name='default template')),
                ('header_content', models.TextField(blank=True, verbose_name='header content')),
                ('footer_content', models.TextField(blank=True, verbose_name='footer content')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='secondary color')),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='font family')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='templates/logos/', verbose_name='logo')),
                ('layout_settings', models.JSONField(blank=True, default=dict, verbose_name='layout settings')),
                ('custom_css', models.TextField(blank=True, verbose_name='custom CSS')),
                ('html_template', models.TextField(blank=True, help_text='Custom HTML template with placeholders', verbose_name='HTML template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
                'ordering': ['-is_default', 'template_type', 'name'],
            },
        ),
    ]
