# Generated by Django 4.2.7 on 2025-10-08 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice Email'), ('offer', 'Offer Email'), ('custom', 'Custom Email'), ('reminder', 'Payment Reminder'), ('welcome', 'Welcome Email'), ('follow_up', 'Follow-up Email')], max_length=20, verbose_name='template type')),
                ('subject', models.CharField(help_text='Can include template variables like {{contact_name}}', max_length=500, verbose_name='email subject')),
                ('html_content', models.TextField(help_text='HTML email body with template variables', verbose_name='HTML content')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text fallback (auto-generated if empty)', verbose_name='plain text version')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default for this type', verbose_name='default template')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='AI generated')),
                ('ai_prompt', models.TextField(blank=True, help_text='Original prompt used to generate this template', verbose_name='AI prompt')),
                ('times_sent', models.IntegerField(default=0, verbose_name='times sent')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['-is_default', 'template_type', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
