# Generated by Django 4.2.7 on 2025-10-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('invoice_date', models.DateField(verbose_name='invoice date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('client_name', models.CharField(max_length=200, verbose_name='client name')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='client email')),
                ('client_address', models.TextField(blank=True, verbose_name='client address')),
                ('client_vat_number', models.CharField(blank=True, max_length=50, verbose_name='client VAT number')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='tax rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='paid amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='invoices/qr_codes/', verbose_name='QR code')),
                ('payment_url', models.URLField(blank=True, help_text='Stripe payment link', verbose_name='payment URL')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('terms', models.TextField(blank=True, verbose_name='terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=50, unique=True, verbose_name='offer number')),
                ('offer_date', models.DateField(verbose_name='offer date')),
                ('valid_until', models.DateField(verbose_name='valid until')),
                ('client_name', models.CharField(max_length=200, verbose_name='client name')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='client email')),
                ('client_address', models.TextField(blank=True, verbose_name='client address')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='tax rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('terms', models.TextField(blank=True, verbose_name='terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='crm.contact')),
                ('converted_to_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_offer', to='invoices.invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'ordering': ['-offer_date', '-offer_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20, verbose_name='payment method')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_matched', models.BooleanField(default=False, verbose_name='matched to invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='unit price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.offer')),
            ],
            options={
                'verbose_name': 'offer item',
                'verbose_name_plural': 'offer items',
                'ordering': ['offer', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='unit price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'ordering': ['invoice', 'order'],
            },
        ),
    ]
