# Generated by Django 4.2.7 on 2025-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='offer',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent at'),
        ),
    ]
