# Generated by Django 4.2.7 on 2025-10-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='plan')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=20, verbose_name='status')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe customer ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancel at period end')),
                ('ai_requests_used', models.IntegerField(default=0, verbose_name='AI requests used this month')),
                ('ai_requests_reset_date', models.DateField(blank=True, null=True, verbose_name='AI requests reset date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_plan', models.CharField(max_length=20, verbose_name='from plan')),
                ('to_plan', models.CharField(max_length=20, verbose_name='to plan')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription history',
                'verbose_name_plural': 'subscription histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe invoice ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount due')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('invoice_pdf', models.URLField(blank=True, verbose_name='invoice PDF')),
                ('hosted_invoice_url', models.URLField(blank=True, verbose_name='hosted invoice URL')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='period end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'subscription invoice',
                'verbose_name_plural': 'subscription invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
