# Generated by Django 4.2.7 on 2025-10-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='име')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='име (английски)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('icon', models.CharField(default='bi-question-circle', help_text='Bootstrap icon класс (напр. bi-envelope)', max_length=50, verbose_name='икона')),
                ('order', models.IntegerField(default=0, verbose_name='ред')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='въпрос')),
                ('question_en', models.CharField(blank=True, max_length=500, verbose_name='въпрос (английски)')),
                ('answer', models.TextField(help_text='Markdown формат', verbose_name='отговор')),
                ('answer_en', models.TextField(blank=True, help_text='Markdown формат', verbose_name='отговор (английски)')),
                ('guide_file', models.CharField(blank=True, help_text='Име на MD файл в faq/guides/ (напр. stripe-setup.md)', max_length=200, verbose_name='файл с ръководство')),
                ('order', models.IntegerField(default=0, verbose_name='ред')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('views_count', models.IntegerField(default=0, verbose_name='брой прегледи')),
                ('is_featured', models.BooleanField(default=False, verbose_name='препоръчан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faq.faqcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'въпрос',
                'verbose_name_plural': 'въпроси',
                'ordering': ['category', 'order', 'question'],
            },
        ),
    ]
